import type { StoreProduct } from "@/lib/types";

export const fallbackProducts: StoreProduct[] = [
  {
    id: "p1",
    variantId: "",
    name: "Luxe Nano Pro",
    handle: "luxe-nano-pro",
    sku: "VPE-001",
    category: "Devices",
    price: 44.99,
    stock: 18,
    description: "Compact adjustable pod system with all-day battery life and a crisp draw.",
    image: "https://images.unsplash.com/photo-1604754742629-3e5728249d73?auto=format&fit=crop&w=1200&q=85",
    accent: "#f4ff35",
    signals: [
      { label: "Battery", value: "All day" },
      { label: "Charge", value: "USB-C" },
      { label: "Pickup", value: "15 min" },
    ],
  },
  {
    id: "p2",
    variantId: "",
    name: "Nova Pod X",
    handle: "nova-pod-x",
    sku: "VPE-002",
    category: "Pod Systems",
    price: 34.99,
    stock: 9,
    description: "Pocket-ready pod system with fast USB-C charging and mesh-coil flavor.",
    image: "https://images.unsplash.com/photo-1576086213369-97a306d36557?auto=format&fit=crop&w=1200&q=85",
    accent: "#ffd84a",
    signals: [
      { label: "Coil", value: "Mesh" },
      { label: "Body", value: "Pocket" },
      { label: "Stock", value: "Low" },
    ],
  },
  {
    id: "p3",
    variantId: "",
    name: "Fogger 8000",
    handle: "fogger-8000",
    sku: "DSP-001",
    category: "Disposables",
    price: 19.99,
    stock: 24,
    description: "Rechargeable disposable with a bright display and smooth consistent output.",
    image: "https://images.unsplash.com/photo-1527281400683-1aae777175f8?auto=format&fit=crop&w=1200&q=85",
    accent: "#f4ff35",
    signals: [
      { label: "Puffs", value: "8000" },
      { label: "Display", value: "Live" },
      { label: "Power", value: "Boost" },
    ],
  },
  {
    id: "p4",
    variantId: "",
    name: "Pulse Bar",
    handle: "pulse-bar",
    sku: "DSP-002",
    category: "Disposables",
    price: 12.99,
    stock: 4,
    description: "A compact grab-and-go device available in rotating flavor drops.",
    image: "https://images.unsplash.com/photo-1563227812-0ea4c22e6cc8?auto=format&fit=crop&w=1200&q=85",
    accent: "#ffd84a",
    signals: [
      { label: "Drop", value: "Limited" },
      { label: "Format", value: "Pocket" },
      { label: "Left", value: "4" },
    ],
  },
  {
    id: "p5",
    variantId: "",
    name: "Charge Case",
    handle: "charge-case",
    sku: "ACC-001",
    category: "Accessories",
    price: 24.99,
    stock: 7,
    description: "Protective charging case that keeps compatible devices powered between stops.",
    image: "/product-placeholder.svg",
    accent: "#f4ff35",
    signals: [
      { label: "Shell", value: "Hard" },
      { label: "Charge", value: "Fast" },
      { label: "Ready", value: "Today" },
    ],
  },
  {
    id: "p6",
    variantId: "",
    name: "EXO Tank",
    handle: "exo-tank",
    sku: "ACC-002",
    category: "Accessories",
    price: 29.99,
    stock: 0,
    description: "Durable replacement tank with adjustable airflow and easy top fill.",
    image: "https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&w=1200&q=85",
    accent: "#ffd84a",
    signals: [
      { label: "Airflow", value: "Adjust" },
      { label: "Fill", value: "Top" },
      { label: "Status", value: "Restock" },
    ],
  },
];
