import type { StoreProduct } from "@/lib/types";

export const fallbackProducts: StoreProduct[] = [
  {
    id: "geek-miami",
    variantId: "",
    name: "GEEK BAR Pulse X — Miami Mint",
    handle: "geek-bar-pulse-x-miami-mint",
    sku: "GB-PX-MIAMI-MINT",
    category: "GEEK BAR",
    brand: "GEEK BAR",
    line: "Pulse X",
    flavor: "Miami Mint",
    nicotine: "5%",
    puffs: "25K",
    price: 24.99,
    stock: 0,
    description: "Cool Miami mint on the Pulse X dual-mesh platform with a curved display and USB-C quick charging.",
    image: "https://oss.geekbar.com/products/pulsex/13.png",
    accent: "#dfff44",
    signals: [{ label: "Puffs", value: "25K" }, { label: "Nicotine", value: "5%" }, { label: "Pickup", value: "15 min" }],
  },
  {
    id: "geek-rancher",
    variantId: "",
    name: "GEEK BAR Pulse X — Blue Rancher",
    handle: "geek-bar-pulse-x-blue-rancher",
    sku: "GB-PX-BLUE-RANCHER",
    category: "GEEK BAR",
    brand: "GEEK BAR",
    line: "Pulse X",
    flavor: "Blue Rancher",
    nicotine: "5%",
    puffs: "25K",
    price: 24.99,
    stock: 0,
    description: "Bold blue candy flavor with regular and Pulse modes, dual mesh coils, and a live curved display.",
    image: "https://oss.geekbar.com/products/pulsex/12.png",
    accent: "#dfff44",
    signals: [{ label: "Puffs", value: "25K" }, { label: "Nicotine", value: "5%" }, { label: "Pickup", value: "15 min" }],
  },
  {
    id: "geek-bpop",
    variantId: "",
    name: "GEEK BAR Pulse X — Strawberry B-Pop",
    handle: "geek-bar-pulse-x-strawberry-b-pop",
    sku: "GB-PX-STRAWBERRY-BPOP",
    category: "GEEK BAR",
    brand: "GEEK BAR",
    line: "Pulse X",
    flavor: "Strawberry B-Pop",
    nicotine: "5%",
    puffs: "25K",
    price: 24.99,
    stock: 0,
    description: "Strawberry candy and ice in GEEK BAR's 18 mL Pulse X platform with dual mesh and quick charge.",
    image: "https://oss.geekbar.com/products/pulsex/14.png",
    accent: "#dfff44",
    signals: [{ label: "Puffs", value: "25K" }, { label: "Nicotine", value: "5%" }, { label: "Pickup", value: "15 min" }],
  },
  {
    id: "raz-razzle",
    variantId: "",
    name: "RAZ DC25000 / LTX 25K — Razzle Dazzle",
    handle: "raz-ltx-25k-razzle-dazzle",
    sku: "RAZ-LTX25K-RAZZLE-DAZZLE",
    category: "RAZ",
    brand: "RAZ",
    line: "DC25000 / LTX 25K",
    flavor: "Razzle Dazzle",
    nicotine: "5%",
    puffs: "25K",
    price: 22.99,
    stock: 0,
    description: "Sweet raspberry, bright lime, and a light cool finish in the RAZ dual-mode 25K platform.",
    image: "https://www.raz-vape.com/wp-content/uploads/2026/03/Razzle-Dazzle-Raz-LTX-25K.webp",
    accent: "#74e8ff",
    signals: [{ label: "Puffs", value: "25K" }, { label: "Nicotine", value: "5%" }, { label: "Pickup", value: "15 min" }],
  },
  {
    id: "raz-blue",
    variantId: "",
    name: "RAZ VUE 50K — Blue Raz Ice",
    handle: "raz-vue-50k-blue-raz-ice",
    sku: "RAZ-VUE50K-BLUE-RAZ-ICE",
    category: "RAZ",
    brand: "RAZ",
    line: "VUE 50K",
    flavor: "Blue Raz Ice",
    nicotine: "5%",
    puffs: "50K",
    price: 23.99,
    stock: 0,
    description: "Blue raspberry candy with a clean ice finish in the reusable RAZ VUE battery-and-pod platform.",
    image: "https://www.raz-vape.com/wp-content/uploads/2026/02/Blue-Raz-Ice-RAZ-VUE-50K-Kit.webp",
    accent: "#74e8ff",
    signals: [{ label: "Puffs", value: "50K" }, { label: "Nicotine", value: "5%" }, { label: "Pickup", value: "15 min" }],
  },
  {
    id: "raz-ruby",
    variantId: "",
    name: "RAZ TN9000 — Ruby",
    handle: "raz-tn9000-ruby",
    sku: "RAZ-TN9000-RUBY",
    category: "RAZ",
    brand: "RAZ",
    line: "TN9000",
    flavor: "Ruby",
    nicotine: "5%",
    puffs: "9K",
    price: 19.99,
    stock: 0,
    description: "Strawberry, black cherry, and raspberry in the compact, draw-activated RAZ TN9000.",
    image: "https://www.raz-vape.com/wp-content/uploads/2025/09/8dc04cb473b65e7c1391663bda5bc1e2.webp",
    accent: "#74e8ff",
    signals: [{ label: "Puffs", value: "9K" }, { label: "Nicotine", value: "5%" }, { label: "Pickup", value: "15 min" }],
  },
];
