import React,{useEffect,useMemo,useRef,useState} from 'react';
import {Link,NavLink,Navigate,Route,Routes,useLocation,useNavigate} from 'react-router-dom';
import {products,updates} from './data.js';
import logoMark from './assets/up-n-smoke-logo.png';
import {STORE_ADDRESS,TAX_RATE} from './operations.js';
import {isMedusaConfigured,loadMedusaCatalog} from './lib/catalog.js';
import {addVariantToCart,cartItemsForStorefront,completePickupCart,getOrCreateCart,importInventoryWorkbook,isEmployeeSignedIn,registerCustomer,signInCustomer,signInEmployee,signOutEmployee,updateCartLine} from './lib/commerce.js';

const Arrow=()=> <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 12h13M13 6l6 6-6 6"/></svg>;
const MenuIcon=()=> <span className="menuIcon"><i/><i/></span>;

function Header({cart,setCart}){
 const [open,setOpen]=useState(false); const loc=useLocation();
 useEffect(()=>setOpen(false),[loc.pathname]);
 return <><header><button className="roundBtn" onClick={()=>setOpen(true)} aria-label="Open menu"><MenuIcon/></button><Link className="logo" to="/" aria-label="UP N SMOKE VAPORS home"><img src={logoMark} alt="UP N SMOKE VAPORS"/></Link><div className="headerRight"><span className="pickupTime">PICKUP: 15—20 MIN</span><Link to="/cart" className="cart">CART <b>{cart}</b></Link></div></header>
 <div className={`drawer ${open?'open':''}`} aria-hidden={!open}><div className="drawerTop"><img src={logoMark} alt="UP N SMOKE VAPORS"/><button className="close" onClick={()=>setOpen(false)}>CLOSE ×</button></div><nav>{[['/','HOME'],['/menu','MENU'],['/updates','UPDATES'],['/about','ABOUT'],['/login','CUSTOMER LOGIN'],['/employee','EMPLOYEE LOGIN']].map(([to,label],i)=><NavLink key={to} to={to}><span>0{i+1}</span>{label}<Arrow/></NavLink>)}</nav><p>Reserve online. Pick up in store.</p></div>{open?<button className="scrim" aria-label="Close menu" onClick={()=>setOpen(false)}/>:null}</>
}

function Reveal({children,className=''}){const ref=useRef(null);useEffect(()=>{const el=ref.current;const io=new IntersectionObserver(([e])=>{if(e.isIntersecting)el.classList.add('visible')},{threshold:.12});io.observe(el);return()=>io.disconnect()},[]);return <div ref={ref} className={`reveal ${className}`}>{children}</div>}

function ProductCard({p,onAdd}){const available=p.stock>0;return <article className={`productCard ${available?'':'soldOut'}`}><div className="productImage"><img src={p.img} alt="" loading="lazy"/><button disabled={!available} aria-label={available?`Add ${p.name} for pickup`:`${p.name} sold out`} onClick={()=>onAdd(p)}>{available?'+':'×'}</button></div><div className="productMeta"><div><h3>{p.name}</h3><small>{p.category}</small></div><strong>${p.price}</strong></div><span className="stock">● {available?`${p.stock} IN STOCK · READY IN 15—20 MIN`:'SOLD OUT'}</span></article>}

function ParticleHero(){const canvas=useRef(null);useEffect(()=>{const c=canvas.current,ctx=c.getContext('2d');let raf,pts=[];const resize=()=>{c.width=c.offsetWidth*devicePixelRatio;c.height=c.offsetHeight*devicePixelRatio;pts=Array.from({length:55},(_,i)=>({x:Math.random()*c.width,y:Math.random()*c.height,r:(i%5+1)*devicePixelRatio,v:(Math.random()-.5)*.35*devicePixelRatio}))};resize();addEventListener('resize',resize);const draw=()=>{ctx.clearRect(0,0,c.width,c.height);ctx.strokeStyle='#9ba80045';ctx.fillStyle='#9ba800';pts.forEach((p,i)=>{p.y+=p.v;if(p.y<0||p.y>c.height)p.v*=-1;ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,7);ctx.fill();if(i%5===0){ctx.beginPath();ctx.arc(c.width*.67,c.height*.48,(80+i*3)*devicePixelRatio,0,7);ctx.stroke()}});raf=requestAnimationFrame(draw)};draw();return()=>{cancelAnimationFrame(raf);removeEventListener('resize',resize)}},[]);return <canvas ref={canvas} className="particles"/>}

function Home({onAdd,inventory}){const [slide,setSlide]=useState(0);return <main>
 <section className="hero"><ParticleHero/><div className="heroCopy"><h1>PICK UP<br/>THE FUTURE.</h1><p>Premium vapor essentials, reserved online and waiting at the counter. No shipping. No guessing. Just pickup.</p><Link className="cta" to="/menu">SHOP THE MENU <Arrow/></Link></div><div className="heroProduct"><div className="device"><span>UP N SMOKE</span></div><div className="pedestal"/></div><span className="scrollCue">SCROLL TO IGNITE ↓</span></section>
 <Reveal><section className="steps"><div className="sectionTop"><h2>PICKUP. SIMPLE.</h2><span>01—03</span></div>{[['01','BROWSE','Explore the menu curated for you.'],['02','RESERVE','Place your order for in-store pickup.'],['03','COLLECT','Swing by and we’ll handle the rest.']].map(x=><article key={x[0]}><b>{x[0]}</b><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</section></Reveal>
 <Reveal><section className="featured"><div className="sectionTop"><h2>FEATURED PICKS</h2><div><button aria-label="Previous" onClick={()=>setSlide(s=>(s+inventory.length-1)%inventory.length)}>←</button><button aria-label="Next" onClick={()=>setSlide(s=>(s+1)%inventory.length)}>→</button></div></div><div className="productRail" style={{transform:`translateX(-${slide*20}%)`}}>{inventory.map(p=><ProductCard p={p} key={p.id} onAdd={onAdd}/>)}</div></section></Reveal>
 <Stats/><UpdatesPreview/><Newsletter/>
 </main>}

function Stats(){return <Reveal><section className="stats">{[['8500','ORDERS FULFILLED'],['98','PICKUP SATISFACTION'],['15','AVG. PICKUP MINUTES'],['4.9','GOOGLE RATING']].map(([n,l],i)=><Counter key={l} end={n} suffix={i===0?'+':i===1?'%':i===3?'★':''} label={l}/>)}</section></Reveal>}
function Counter({end,suffix,label}){const [n,setN]=useState(0),ref=useRef();useEffect(()=>{const io=new IntersectionObserver(([e])=>{if(e.isIntersecting){let s=performance.now();const run=t=>{const p=Math.min(1,(t-s)/1200);setN((+end*p).toFixed(end.includes('.')?1:0));if(p<1)requestAnimationFrame(run)};requestAnimationFrame(run);io.disconnect()}},{threshold:.5});io.observe(ref.current);return()=>io.disconnect()},[end]);return <div ref={ref}><strong>{Number(n).toLocaleString()}{suffix}</strong><span>{label}</span></div>}
function UpdatesPreview(){return <Reveal><section className="updatesPreview"><div className="sectionTop"><h2>UPDATES & DROPS</h2><Link to="/updates">VIEW ALL</Link></div><div className="updateGrid">{updates.slice(0,3).map(u=><article key={u.title}><img src={u.img} alt=""/><div><small>{u.date}</small><h3>{u.title}</h3><p>{u.text}</p><Link to="/updates">READ MORE →</Link></div></article>)}</div></section></Reveal>}
function Newsletter(){const [done,setDone]=useState(false);return <section className="newsletter"><div><h2>STAY IN THE LOOP</h2><p>New drops, exclusive perks, and store updates.</p></div>{done?<strong>YOU’RE ON THE LIST ✓</strong>:<form onSubmit={e=>{e.preventDefault();setDone(true)}}><label className="srOnly" htmlFor="email">Email address</label><input id="email" required type="email" placeholder="Email address"/><button>SUBSCRIBE <Arrow/></button></form>}</section>}

function MenuPage({onAdd,inventory}){const [cat,setCat]=useState('All');const cats=['All',...new Set(inventory.map(p=>p.category))];const shown=useMemo(()=>cat==='All'?inventory:inventory.filter(p=>p.category===cat),[cat,inventory]);return <main className="page"><div className="pageTitle"><h1>THE MENU</h1><p>Live local inventory is shown below. Sold-out products cannot be reserved.</p></div><div className="filters">{cats.map(c=><button className={c===cat?'active':''} onClick={()=>setCat(c)} key={c}>{c}</button>)}</div><div className="catalog">{shown.map(p=><ProductCard p={p} key={p.id} onAdd={onAdd}/>)}</div></main>}
function UpdatesPage(){return <main className="page"><div className="pageTitle"><h1>UPDATES</h1><p>The latest from the counter: drops, hours, and member perks.</p></div><section className="timeline">{updates.map((u,i)=><Reveal key={u.title}><article><div className="date">{u.date}</div><div><span>0{i+1}</span><h2>{u.title}</h2><p>{u.text}</p></div><img src={u.img} alt=""/></article></Reveal>)}</section></main>}
function About(){return <main className="page"><div className="pageTitle"><h1>ABOUT US</h1><p>Built for the future of convenience. Rooted in our neighborhood.</p></div><section className="aboutIntro"><div><h2>MORE CHOICE.<br/>LESS WAIT.</h2><p>UP N SMOKE VAPORS was built around one simple idea: your time matters. We pair a deep, carefully selected menu with fast in-store pickup and people who know the products.</p></div><img src="https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=1400&q=80" alt="Modern retail store interior"/></section><section className="storeInfo"><article><small>HOURS</small><h3>MON—THU 10AM—9PM<br/>FRI—SAT 10AM—10PM<br/>SUNDAY 11AM—8PM</h3></article><article><small>LOCATION</small><h3>125 VAPOR WAY<br/>YOURTOWN, ST 12345</h3><a href="https://maps.google.com" target="_blank">GET DIRECTIONS →</a></article></section><section className="quotes">{['Best selection and the fastest pickup in town. Always my go-to.','Staff is knowledgeable and the rewards program is legit.','My order is ready every time. That’s how it should be.'].map((q,i)=><blockquote key={q}>★★★★★<p>“{q}”</p><cite>— {['J.M.','K.T.','D.R.'][i]}</cite></blockquote>)}</section></main>}

function CartPage({cart,inventory,onQuantity}){const rows=cart.map(item=>({...item,product:inventory.find(p=>p.id===item.id)})).filter(x=>x.product);const subtotal=rows.reduce((sum,x)=>sum+x.product.price*x.qty,0);return <main className="page cartPage"><div className="pageTitle"><h1>YOUR PICKUP</h1><p>Review your reservation before choosing a pickup window.</p></div>{rows.length===0?<section className="emptyState"><h2>YOUR BAG IS QUIET.</h2><p>Add something from the menu and it’ll be waiting here.</p><Link className="cta" to="/menu">BROWSE THE MENU <Arrow/></Link></section>:<div className="cartLayout"><section className="cartItems">{rows.map(({product,qty,lineItemId})=><article key={product.id}><img src={product.img} alt=""/><div><small>{product.sku}</small><h2>{product.name}</h2><span>${product.price.toFixed(2)}</span></div><div className="qtyControl"><button onClick={()=>onQuantity(lineItemId,qty-1)}>−</button><b>{qty}</b><button disabled={qty>=product.stock} onClick={()=>onQuantity(lineItemId,qty+1)}>+</button></div><strong>${(product.price*qty).toFixed(2)}</strong></article>)}</section><aside className="orderSummary"><h2>ORDER SUMMARY</h2><p><span>Subtotal</span><b>${subtotal.toFixed(2)}</b></p><p><span>Estimated tax</span><b>${(subtotal*TAX_RATE).toFixed(2)}</b></p><div><span>TOTAL</span><strong>${(subtotal*(1+TAX_RATE)).toFixed(2)}</strong></div><Link className="cta" to="/checkout">CONTINUE TO PICKUP <Arrow/></Link><small>Age-restricted items require valid ID at pickup.</small></aside></div>}</main>}

function Checkout({cart,inventory,setCart,setInventory}){const [complete,setComplete]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);const rows=cart.map(item=>({...item,product:inventory.find(p=>p.id===item.id)})).filter(x=>x.product);const subtotal=rows.reduce((sum,x)=>sum+x.product.price*x.qty,0),tax=subtotal*TAX_RATE,total=subtotal+tax;const submit=async e=>{e.preventDefault();setBusy(true);setError('');const f=new FormData(e.currentTarget);try{const pickupWindow=f.get('window');const order=await completePickupCart({name:f.get('name'),email:f.get('email'),phone:f.get('phone'),pickupWindow,notes:f.get('notes')});setCart([]);setComplete({id:order.display_id||order.id,pickupWindow});const refreshed=await loadMedusaCatalog();if(refreshed?.length)setInventory(refreshed)}catch(err){setError(err.message)}finally{setBusy(false)}};if(!rows.length&&!complete)return <Navigate to="/cart" replace/>;if(complete)return <main className="page confirmation"><span>ORDER {complete.id}</span><h1>WE’LL TAKE IT<br/>FROM HERE.</h1><p>Your pickup order is now in Medusa. We’ll have it ready during <b>{complete.pickupWindow}</b>.</p><Link className="cta" to="/menu">BACK TO MENU <Arrow/></Link></main>;return <main className="page checkoutPage"><div className="pageTitle"><h1>CHECKOUT</h1><p>Reserve now. Pay with Clover when you collect your order.</p></div><div className="checkoutLayout"><form onSubmit={submit}><h2>CONTACT</h2><div className="fieldGrid"><label>Full name<input name="name" required/></label><label>Phone<input name="phone" required/></label><label>Email receipt<input name="email" type="email" required/></label></div><h2>PICKUP WINDOW</h2><div className="pickupWindows">{['ASAP · 15—20 min','Today · 4:30 PM','Today · 6:00 PM'].map((x,i)=><label key={x}><input type="radio" name="window" value={x} defaultChecked={i===0}/><span>{x}</span></label>)}</div><p className="pickupAddress">PICKUP AT — {STORE_ADDRESS}</p><h2>NOTES</h2><label><textarea name="notes" placeholder="Flavor substitutions or anything staff should know."/></label>{error?<p className="formError">{error}</p>:null}<button className="cta" disabled={busy}>{busy?'PLACING ORDER…':'PLACE PICKUP ORDER'} {!busy?<Arrow/>:null}</button></form><aside className="orderSummary"><h2>SUMMARY</h2>{rows.map(x=><p key={x.id}><span>{x.product.name} × {x.qty}</span><b>${(x.product.price*x.qty).toFixed(2)}</b></p>)}<div><span>TOTAL</span><strong>${total.toFixed(2)}</strong></div><small>Payment is completed in store through Clover.</small></aside></div></main>}
function Login({employee=false}){const [done,setDone]=useState(false),[error,setError]=useState(''),[register,setRegister]=useState(false),[busy,setBusy]=useState(false);const navigate=useNavigate();const submit=async e=>{e.preventDefault();setBusy(true);setError('');const values=new FormData(e.currentTarget);try{if(employee){await signInEmployee(values.get('email'),values.get('password'));navigate('/admin');return}if(register){await registerCustomer({first_name:values.get('first_name'),last_name:values.get('last_name'),email:values.get('email'),password:values.get('password')})}else{await signInCustomer(values.get('email'),values.get('password'))}setDone(true)}catch(err){setError(err.message)}finally{setBusy(false)}};return <main className="loginPage"><section className="loginVisual"><h1>{employee?'TEAM ACCESS.':'WELCOME BACK.'}</h1><p>{employee?'Secure Medusa inventory operations and daily workbook imports.':'Your pickup orders and account are secured by Medusa.'}</p><div className="loginOrb">UNS</div></section><section className="loginForm"><small>{employee?'EMPLOYEE PORTAL':'CUSTOMER ACCOUNT'}</small><h2>{done?'ACCESS GRANTED.':register?'CREATE ACCOUNT':'SIGN IN'}</h2>{error?<p className="formError">{error}</p>:null}{done?<p>You are signed in through Medusa.</p>:<form onSubmit={submit}>{register?<div className="fieldGrid"><label>First name<input name="first_name" required/></label><label>Last name<input name="last_name" required/></label></div>:null}<label>Email address<input name="email" required type="email" autoComplete="username" defaultValue={employee?'admin@upnsmoke.local':''}/></label><label>Password<input name="password" required type="password" autoComplete="current-password"/></label><button disabled={busy}>{busy?'PLEASE WAIT…':register?'CREATE ACCOUNT':'LOG IN'} {!busy?<Arrow/>:null}</button></form>}{!employee&&!done?<button className="textButton" onClick={()=>{setRegister(value=>!value);setError('')}}>{register?'HAVE AN ACCOUNT? SIGN IN →':'NEW HERE? CREATE AN ACCOUNT →'}</button>:null}</section></main>}

function Admin(){const navigate=useNavigate(),[file,setFile]=useState(null),[result,setResult]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);if(!isEmployeeSignedIn())return <Navigate to="/employee" replace/>;const run=async dryRun=>{if(!file)return;setBusy(true);setError('');try{setResult(await importInventoryWorkbook(file,dryRun))}catch(err){setError(err.message)}finally{setBusy(false)}};const changeCount=(result?.matched_count||0)+(result?.created_count||0)+(result?.level_count||0);return <main className="adminPage"><div className="adminHead"><div><small>MEDUSA EMPLOYEE OPERATIONS</small><h1>DAILY INVENTORY</h1><p>Preview every workbook before updating live storefront stock.</p></div><div className="adminActions"><a href="http://localhost:9000/app" target="_blank">OPEN MEDUSA ADMIN ↗</a><Link to="/menu">VIEW STOREFRONT ↗</Link><button onClick={()=>{signOutEmployee();navigate('/employee')}}>LOG OUT</button></div></div><section className="importPanel"><h2>CLOVER XLSX → MEDUSA</h2><p>Upload Clover’s full inventory export or the simple SKU template. Existing SKUs get new stock counts; missing SKUs are created with Clover names, prices, categories, and visibility.</p><a className="cta" href="/UP-N-SMOKE-Medusa-Inventory-Template.xlsx" download>DOWNLOAD SIMPLE TEMPLATE <Arrow/></a><label className="fileDrop">{file?file.name:'SELECT CLOVER XLSX'}<input type="file" accept=".xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" onChange={event=>{setFile(event.target.files?.[0]||null);setResult(null);setError('')}}/></label><div className="adminActions inlineActions"><button disabled={!file||busy} onClick={()=>run(true)}>{busy?'READING…':'PREVIEW IMPORT'}</button>{result?.dry_run&&changeCount>0?<button disabled={busy} onClick={()=>run(false)}>APPLY {changeCount} CHANGES</button>:null}</div>{error?<p className="formError">{error}</p>:null}{result?<div className="importResults"><strong>{result.dry_run?'PREVIEW READY':'MEDUSA UPDATED'} · {result.total_rows} ROWS · {result.matched_count} STOCK UPDATES · {result.created_count||0} NEW PRODUCTS</strong>{result.matched?.slice(0,12).map(row=><p key={`matched-${row.sku}`}><b>{row.sku}</b><span>{row.previous_quantity} → {row.quantity}</span></p>)}{result.created?.slice(0,12).map(row=><p key={`created-${row.sku}`}><b>{row.sku}</b><span>CREATE {row.name} · QTY {row.quantity}</span></p>)}{changeCount>24?<p><b>+ {changeCount-24} more</b><span>Included when applied</span></p>:null}</div>:null}</section></main>}
function Footer(){return <footer><span>© 2026 UP N SMOKE VAPORS. ALL RIGHTS RESERVED.</span><div><a href="#instagram">INSTAGRAM</a><a href="#facebook">FACEBOOK</a><a href="#privacy">PRIVACY</a></div></footer>}

function useMedusaCatalog(setInventory){const [status,setStatus]=useState(isMedusaConfigured?'connecting':'local');useEffect(()=>{if(!isMedusaConfigured)return;let active=true;const refresh=()=>loadMedusaCatalog().then(items=>{if(active&&items?.length){setInventory(items);setStatus('connected')}}).catch(()=>active&&setStatus('offline'));refresh();const interval=setInterval(refresh,60000);addEventListener('focus',refresh);return()=>{active=false;clearInterval(interval);removeEventListener('focus',refresh)}},[setInventory]);return status}

export default function App(){const [cart,setCart]=useState([]),[toast,setToast]=useState(''),[inventory,setInventory]=useState(products);const medusaStatus=useMedusaCatalog(setInventory),loc=useLocation();useEffect(()=>{scrollTo({top:0,behavior:'smooth'})},[loc.pathname]);useEffect(()=>{if(medusaStatus!=='connected')return;let active=true;getOrCreateCart().then(remote=>{if(active)setCart(cartItemsForStorefront(remote,inventory))}).catch(()=>{});return()=>{active=false}},[medusaStatus,inventory]);const showToast=message=>{setToast(message);setTimeout(()=>setToast(''),1800)};const add=async p=>{if(p.stock<1||!p.variantId)return;try{const remote=await addVariantToCart(p.variantId);setCart(cartItemsForStorefront(remote,inventory));showToast(`${p.name} added for pickup`)}catch(err){showToast(err.message)}};const changeQuantity=async(lineItemId,quantity)=>{try{const remote=await updateCartLine(lineItemId,quantity);setCart(cartItemsForStorefront(remote,inventory))}catch(err){showToast(err.message)}};const cartCount=cart.reduce((sum,x)=>sum+x.qty,0);return <><Header cart={cartCount}/><div className={`medusaStatus ${medusaStatus}`}>{medusaStatus==='connected'?'MEDUSA LIVE':medusaStatus==='connecting'?'CONNECTING MEDUSA':medusaStatus==='offline'?'MEDUSA OFFLINE · LOCAL CACHE':'LOCAL DEMO DATA'}</div><Routes><Route path="/" element={<Home onAdd={add} inventory={inventory}/>}/><Route path="/menu" element={<MenuPage onAdd={add} inventory={inventory}/>}/><Route path="/cart" element={<CartPage cart={cart} inventory={inventory} onQuantity={changeQuantity}/>}/><Route path="/checkout" element={<Checkout cart={cart} inventory={inventory} setCart={setCart} setInventory={setInventory}/>}/><Route path="/updates" element={<UpdatesPage/>}/><Route path="/about" element={<About/>}/><Route path="/login" element={<Login/>}/><Route path="/employee" element={<Login employee/>}/><Route path="/admin" element={<Admin/>}/></Routes><Footer/><button className="backTop" onClick={()=>scrollTo({top:0,behavior:'smooth'})}>↑</button>{toast?<div className="toast">{toast}</div>:null}</>}
